### ISSUE TITLE
MISP object template for DFXML

### ISSUE THREAD

**Issue by adulau** [simsong/dfxml#30]
We are looking to add the DFXML format in [MISP](https://github.com/MISP/MISP) (especially to have a set of [MISP object templates](https://www.misp-project.org/objects.html) to map DFXML when people share forensic acquisition).

Before doing the JSON object template, I was wondering if someone already did a version of DFXML in JSON and if there is a JSON schema available. If not, I will use the XML DTD as a reference.

Thanks a lot for your work.

**Comment by ajnelson-nist** [comment]
Hi, and thanks!

I don't know of any JSON renders of DFXML.  There is [some work](https://github.com/ajnelson-nist/case-implementation-dfxml) going into translating DFXML back and forth between [CASE](https://github.com/ucoProject/CASE) and the [Unified Cyber Ontology](https://github.com/ucoProject/UCO), which are RDF-based and can use JSON-LD as a transport/serialization language.

If you'd like to render DFXML as JSON, I would not use the DTD as a reference, as it hasn't been updated in quite some time.  The [DFXML Schema](https://github.com/dfxml-working-group/dfxml_schema) defines the language and validates documents with `xmllint`, so that would better serve as a reference.

I guess while we're thinking about it: @simsong , would you be alright with retiring the [DTD](https://github.com/simsong/dfxml/blob/master/dtd/dfxml.dtd)?

**Comment by simsong** [comment]
I’m fine with killing the DTD.


----
Sent from my phone.

On Jul 25, 2018, at 3:21 PM, Alex Nelson <notifications@github.com> wrote:

Hi, and thanks!

I don't know of any JSON renders of DFXML. There is some work going into translating DFXML back and forth between CASE and the Unified Cyber Ontology, which are RDF-based and can use JSON-LD as a transport/serialization language.

If you'd like to render DFXML as JSON, I would not use the DTD as a reference, as it hasn't been updated in quite some time. The DFXML Schema defines the language and validates documents with xmllint, so that would better serve as a reference.

I guess while we're thinking about it: @simsong , would you be alright with retiring the DTD?

**Comment by adulau** [comment]
Thank you very much for the quick feedback.

I will use [dfxml.xsd](https://github.com/dfxml-working-group/dfxml_schema/blob/master/dfxml.xsd) as reference. It would be really useful to have some sample DFXML files next to the schema to see how they are practically used.

**Comment by simsong** [comment]
What about these samples?

https://github.com/simsong/dfxml/tree/master/samples <https://github.com/simsong/dfxml/tree/master/samples>

**Comment by adulau** [comment]
Thank you. Sorry ;-)
